/*
 * BGT60TR13C register configuration for LFSR data test.
 *
 * Generated by bgt60-configurator-cli (SDK v3.6.4) from:
 *   {
 *     "device_config": {
 *       "fmcw_single_shape": {
 *         "rx_antennas": [1],
 *         "tx_antennas": [1],
 *         "tx_power_level": 31,
 *         "if_gain_dB": 60,
 *         "lower_frequency_Hz": 61020098000,
 *         "upper_frequency_Hz": 61479902000,
 *         "num_chirps_per_frame": 1,
 *         "num_samples_per_chirp": 128,
 *         "chirp_repetition_time_s": 7e-05,
 *         "frame_repetition_time_s": 5e-3,
 *         "sample_rate_Hz": 2330000
 *       }
 *     }
 *   }
 *
 * Each entry is a packed SPI write command:
 *   [31:25] register address, [24] write bit, [23:0] data
 */

#ifndef BGT60TR13C_DEFAULT_CONFIG_H_
#define BGT60TR13C_DEFAULT_CONFIG_H_

#include <stdint.h>

static const uint32_t bgt60tr13c_default_regs[] = {
    0x011e8270UL, 0x03088210UL, 0x09e967fdUL, 0x0b0805b4UL, 0x0d1027ffUL,
    0x0f010700UL, 0x11000000UL, 0x13000000UL, 0x15000000UL, 0x17000be0UL,
    0x19000000UL, 0x1b000000UL, 0x1d000000UL, 0x1f000b60UL, 0x21103c51UL,
    0x231ff41fUL, 0x25006f7bUL, 0x2d000490UL, 0x3b000480UL, 0x49000480UL,
    0x57000480UL, 0x5911be0eUL, 0x5b44c40aUL, 0x5d000000UL, 0x5f787e1eUL,
    0x61f5208aUL, 0x630000a4UL, 0x65000252UL, 0x67000080UL, 0x69000000UL,
    0x6b000000UL, 0x6d000000UL, 0x6f093910UL, 0x7f000100UL, 0x8f000100UL,
    0x9f000100UL, 0xad000000UL, 0xb7000000UL,
};

#define BGT60TR13C_DEFAULT_REGS_LEN ARRAY_SIZE(bgt60tr13c_default_regs)

/*
 * Number of samples per frame for this configuration:
 *   1 RX antenna × 1 chirp × 128 samples = 128
 */
#define BGT60TR13C_DEFAULT_NUM_SAMPLES_PER_FRAME 128

#endif /* BGT60TR13C_DEFAULT_CONFIG_H_ */
