CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_CLOCK_MANAGEMENT=y
CONFIG_CLOCK_MANAGEMENT_RUNTIME=y
#CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="instrumentation_trigger"
#CONFIG_INSTRUMENTATION=y
#CONFIG_INSTRUMENTATION_MODE_CALLGRAPH=y
#CONFIG_INSTRUMENTATION_EXCLUDE_FILE_LIST="isr_wrapper,xip,bitmask,version,spi,i2c,adc,pwm,wdt,usb,mem,cy_crypto,cy_ble,cy_tcpwm,cy_adc,cy_dac,cy_smartio,cy_sdhc,cmsis,crypto,dma,cy_mpc,cy_ppc,cy_trigmux,qspi,bitarray"
#CONFIG_INSTRUMENTATION_EXCLUDE_FUNCTION_LIST="pm_device_runtime_is_enabled,device_is_ready,pm_device_is_busy,pm_device_wakeup_is_enabled,pm_device_action_run,main,k_busy_wait,sys_clock_elapsed,any_cpu_announcing,this_cpu_announcin,runq_bes,next_up,update_cache,sys_clock_cycle_get_32,arch_k_cycle_get_32,k_cycle_get_3,arch_irq_lock,arch_irq_unlock,timeout"
#CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_TRACE_BUFFER_SIZE=65000
#CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_BUFFER_OVERWRITE=y
#CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="instrumentation_stopper"
#CONFIG_INSTRUMENTATION_DYNAMIC_TRIGGER=n