#include <stdio.h>

#include "IfxPmu_reg.h"
#include "IfxPmu_regdef.h"
#include "IfxPmu_bf.h"
#include "Ifx_TypesReg.h"
#include "Ifx_Sfr_test.h"

#ifndef SFR_TEST
int main()
#else
int Pmu_main()
#endif
{
  printf("Compile & execution ok");
  volatile Ifx_UReg_32Bit dummy[3];

/******************************************************************************/
/******************************************************************************/


dummy[0] = PMU_DVFSCTRL.U;
    dummy[0] = PMU_DVFSCTRL.B.DVFSEN;
    dummy[0] = PMU_DVFSCTRL.B.MODESEL;
    dummy[0] = PMU_DVFSCTRL.B.NUMSTATES;
    dummy[0] = PMU_DVFSCTRL.B.TRANSTIMEOUT;

dummy[0] = PMU_DVFSPSTATEREQ.U;
    dummy[0] = PMU_DVFSPSTATEREQ.B.TARGETPSTATE;

dummy[0] = PMU_DVFSSTATUS.U;
    dummy[0] = PMU_DVFSSTATUS.B.CURRPSTATE;
    dummy[0] = PMU_DVFSSTATUS.B.TRANSPENDING;
    dummy[0] = PMU_DVFSSTATUS.B.BUSY;
    dummy[0] = PMU_DVFSSTATUS.B.TRANSPHASE;
    dummy[0] = PMU_DVFSSTATUS.B.ERROR;

dummy[0] = PMU_CURRVOLTMV.U;
    dummy[0] = PMU_CURRVOLTMV.B.VALUE;

dummy[0] = PMU_CURRFREQMHZ.U;
    dummy[0] = PMU_CURRFREQMHZ.B.VALUE;

dummy[0] = PMU_DVFSPSTATETABLE_PSTATE.U;
    dummy[0] = PMU_DVFSPSTATETABLE_PSTATE.B.FREQ;
    dummy[0] = PMU_DVFSPSTATETABLE_PSTATE.B.VOLTAGE;

dummy[0] = IFX_PMU_DVFSCTRL_DVFSEN_LEN;
dummy[1] = IFX_PMU_DVFSCTRL_DVFSEN_MSK;
dummy[2] = IFX_PMU_DVFSCTRL_DVFSEN_OFF;
dummy[0] = IFX_PMU_DVFSCTRL_MODESEL_LEN;
dummy[1] = IFX_PMU_DVFSCTRL_MODESEL_MSK;
dummy[2] = IFX_PMU_DVFSCTRL_MODESEL_OFF;
dummy[0] = IFX_PMU_DVFSCTRL_NUMSTATES_LEN;
dummy[1] = IFX_PMU_DVFSCTRL_NUMSTATES_MSK;
dummy[2] = IFX_PMU_DVFSCTRL_NUMSTATES_OFF;
dummy[0] = IFX_PMU_DVFSCTRL_TRANSTIMEOUT_LEN;
dummy[1] = IFX_PMU_DVFSCTRL_TRANSTIMEOUT_MSK;
dummy[2] = IFX_PMU_DVFSCTRL_TRANSTIMEOUT_OFF;

dummy[0] = IFX_PMU_DVFSPSTATEREQ_TARGETPSTATE_LEN;
dummy[1] = IFX_PMU_DVFSPSTATEREQ_TARGETPSTATE_MSK;
dummy[2] = IFX_PMU_DVFSPSTATEREQ_TARGETPSTATE_OFF;

dummy[0] = IFX_PMU_DVFSSTATUS_CURRPSTATE_LEN;
dummy[1] = IFX_PMU_DVFSSTATUS_CURRPSTATE_MSK;
dummy[2] = IFX_PMU_DVFSSTATUS_CURRPSTATE_OFF;
dummy[0] = IFX_PMU_DVFSSTATUS_TRANSPENDING_LEN;
dummy[1] = IFX_PMU_DVFSSTATUS_TRANSPENDING_MSK;
dummy[2] = IFX_PMU_DVFSSTATUS_TRANSPENDING_OFF;
dummy[0] = IFX_PMU_DVFSSTATUS_BUSY_LEN;
dummy[1] = IFX_PMU_DVFSSTATUS_BUSY_MSK;
dummy[2] = IFX_PMU_DVFSSTATUS_BUSY_OFF;
dummy[0] = IFX_PMU_DVFSSTATUS_TRANSPHASE_LEN;
dummy[1] = IFX_PMU_DVFSSTATUS_TRANSPHASE_MSK;
dummy[2] = IFX_PMU_DVFSSTATUS_TRANSPHASE_OFF;
dummy[0] = IFX_PMU_DVFSSTATUS_ERROR_LEN;
dummy[1] = IFX_PMU_DVFSSTATUS_ERROR_MSK;
dummy[2] = IFX_PMU_DVFSSTATUS_ERROR_OFF;

dummy[0] = IFX_PMU_CURRVOLTMV_VALUE_LEN;
dummy[1] = IFX_PMU_CURRVOLTMV_VALUE_MSK;
dummy[2] = IFX_PMU_CURRVOLTMV_VALUE_OFF;

dummy[0] = IFX_PMU_CURRFREQMHZ_VALUE_LEN;
dummy[1] = IFX_PMU_CURRFREQMHZ_VALUE_MSK;
dummy[2] = IFX_PMU_CURRFREQMHZ_VALUE_OFF;

dummy[0] = IFX_PMU_DVFSPSTATETABLE_PSTATE_FREQ_LEN;
dummy[1] = IFX_PMU_DVFSPSTATETABLE_PSTATE_FREQ_MSK;
dummy[2] = IFX_PMU_DVFSPSTATETABLE_PSTATE_FREQ_OFF;
dummy[0] = IFX_PMU_DVFSPSTATETABLE_PSTATE_VOLTAGE_LEN;
dummy[1] = IFX_PMU_DVFSPSTATETABLE_PSTATE_VOLTAGE_MSK;
dummy[2] = IFX_PMU_DVFSPSTATETABLE_PSTATE_VOLTAGE_OFF;



dummy[0] = dummy[0] + 0;
  return 0;
}
